apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.go.name }}
  {{- template "common.metadata" . }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.go.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.go.name }}
    spec:
      nodeSelector: {{ .Values.nodeSelector }}
      containers:
        - name: {{ .Values.app.go.name }}
          image: {{ .Values.app.go.image }}
          imagePullPolicy: IfNotPresent
          env: 
            - name: AZURESTORAGE_CONNECTION
              value: {{ .Values.env.connStr }}
            - name: OCAGENT_TRACE_EXPORTER_ENDPOINT
              value: "http://localforwarder-oc.aks-webhook-ns:50002"
            - name: SERVICE_NAME 
              value: "go_lf_service"
          ports:
            - containerPort: 50030
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 900m