# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "kube-system"

app:
  name: "app-monitoring-webhook"
  environment: "test"
  owner : "Microsoft"
  image: "mcr.microsoft.com/applicationinsights/codeless-attach/mutating-webhook:test_8_7_2"
  agents: "mcr.microsoft.com/applicationinsights/codeless-attach/mutating-webhook-agents:test_8_6_2"
  caBundle: "baseBundle"
  iKey: "target ikey2"
  telemetryIkey: "de3dca83-58c6-42bc-975d-a0f0fc113fd0"
  telemetryConnString: "InstrumentationKey=de3dca83-58c6-42bc-975d-a0f0fc113fd0"
  testing: false

replicaCount: 2

nodeSelector: "{ \"beta.kubernetes.io/os\": linux }"
